### ISSUE TITLE
HPC-BP webinar checklist: hpcbp-081-securesoftware

### ISSUE THREAD

**Issue by bernhold** [ideas-productivity/ideas-productivity.github.io#51]
**Preparing initial event**
- Collect initial webinar information
  - [x] webinar `startdate`
  - [x] webinat `time`
  - [x] webinar `title`
  - [x] presenter name(s)
  - [x] presenter affiliation(s)
  - [x] presenter bio(s)
  - [x] presenter github id(s)
  - [x] `registration-url`
  - [x] `ecp-abbreviation`
  - [x] webinar abstract
- [x] Technical editor checks webinar abstract
- [x] Create event in `_events-drafts`
- [x] Verify content and formatting
- [x] Move event into `events/hpcbp-webinars/`

**Advertising event**
- [x] Submit BSSw.io event PR
  - Source is in `/internal/events-hpcbp-bsswio/`
  - Destination is <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/tree/master/Events>
- [x] Notify BSSw.io editors of event
  - Source is in `/internal/events-hpcbp-bsswio-digest/`
- Prepare and send MailChimp campaign to full audience
  - [x] ensure that Mailchimp audience is as up-to-date as possible
  - [x] prepare announcement campaign
    - Source is in `/internal/events-hpcbp-mailchimp-annonucement/`
  - [x] schedule distribution of email

**Post-event artifact collection and archiving**
- Collect artifacts in Google Drive
  - [x] webinar registration list
  - [x] webinar participation list
  - [x] slides
  - [x] Q&A
  - [x] recording(s)
  - [ ] additional materials (as necessary)
- Add artifacts to i-p.o website and update event
  - [x] slides
  - [x] Q&A
  - [ ] additional materials (as necessary)
- Publish recording to YouTube
  - [x] upload recording(s) to YouTube
    - Source information is in `/internal/events-hpcbp-youtube/`
  - [x] add YouTube link to event artifacts

**Followup communications**
- [x] Submit BSSw.io curated content PR
  - Source is <https://ideas-productivity.org/internal/hpcbp-webinars/hpcbp-webinars-cc.md>
  - Destination is <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/hpcbp-webinars-cc.md>
- Update MailChimp audience w/ appropriate tag
  - [x] add webinar registrants w/ appropriate tag
  - [x] add webinar participants w/ appropriate tag
- [x] Prepare and send MailChimp followup to appropriate tag
